# Generated by Django 6.1 on 2026-08-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, verbose_name='Shipping address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Shipping postal code'),
        ),
    ]
