# Generated by Django 6.1 on 2026-09-02 14:18

import django.db.models.deletion
import orders.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('surcharge_percent', models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=5, verbose_name='Surcharge %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_design', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='CustomDesignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=orders.models.design_image_path, verbose_name='Image')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.customdesign')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
    ]
