# Generated by Django 6.1 on 2026-09-02 16:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customdesign_customdesignimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdesign',
            name='order_items',
            field=models.ManyToManyField(help_text='The order items this design applies to (each carries the surcharge).', related_name='custom_designs', to='orders.orderitem', verbose_name='Customized order items'),
        ),
        migrations.AddField(
            model_name='customdesign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='surcharge_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Custom-design surcharge %'),
        ),
    ]
