# Generated by Django 6.1 on 2026-08-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_categories',
            field=models.ManyToManyField(blank=True, help_text='Extra categories this product also belongs to (optional).', related_name='additional_products', to='products.category', verbose_name='Additional categories'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_subcategories',
            field=models.ManyToManyField(blank=True, help_text="Extra subcategories this product also belongs to (optional). Each must belong to the product's primary or additional categories.", related_name='additional_products', to='products.subcategory', verbose_name='Additional subcategories'),
        ),
    ]
