# Generated by Django 6.1 on 2026-08-31 17:19

from django.db import migrations, models


def copy_product_categories(apps, schema_editor):
    """Preserve the old single category/subcategory assignments (and the
    temporary 'additional' M2M relations) in the new many-to-many tables."""
    Product = apps.get_model("products", "Product")
    category_through = Product.categories.through
    subcategory_through = Product.subcategories.through
    for product in Product.objects.all().iterator():
        category_ids = list(product.additional_categories.values_list("pk", flat=True))
        if product.category_id:
            category_ids.append(product.category_id)
        category_through.objects.bulk_create(
            category_through(product=product, category_id=category_id)
            for category_id in dict.fromkeys(category_ids)
        )
        subcategory_ids = list(
            product.additional_subcategories.values_list("pk", flat=True)
        )
        if product.subcategory_id:
            subcategory_ids.append(product.subcategory_id)
        subcategory_through.objects.bulk_create(
            subcategory_through(product=product, subcategory_id=subcategory_id)
            for subcategory_id in dict.fromkeys(subcategory_ids)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_additional_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='The categories this product belongs to (a product may belong to several).', related_name='products', to='products.category', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(blank=True, help_text="The subcategories this product belongs to (a product may belong to several). Each must belong to one of the product's categories.", related_name='products', to='products.subcategory', verbose_name='Subcategories'),
        ),
        # Copy the old FK/M2M assignments into the new tables BEFORE the old
        # fields are dropped, so no data is lost.
        migrations.RunPython(copy_product_categories, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='additional_categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='additional_subcategories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
