# Generated by Django 6.1 on 2026-10-03 10:11

import products.fields
from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    database = schema_editor.connection.alias
    Product = apps.get_model("products", "Product")
    Subcategory = apps.get_model("products", "Subcategory")

    for model, scope_fields in ((Product, ()), (Subcategory, ("category_id",))):
        queryset = model.objects.using(database)
        for instance in queryset.order_by("pk").iterator():
            base_slug = slugify(instance.name, allow_unicode=True) or "item"
            slug = base_slug
            suffix = 2
            scope = {field: getattr(instance, field) for field in scope_fields}
            while queryset.filter(**scope, slug=slug).exclude(pk=instance.pk).exists():
                slug = f"{base_slug}-{suffix}"
                suffix += 1
            queryset.filter(pk=instance.pk).update(slug=slug)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_additional_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=products.fields.AutoSlugField(allow_unicode=True, blank=True, db_index=False, default='', editable=False, max_length=250),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=products.fields.AutoSlugField(allow_unicode=True, blank=True, db_index=False, default='', editable=False, max_length=150, unique_scope=('category',)),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=products.fields.AutoSlugField(allow_unicode=True, blank=True, db_index=False, default='', editable=False, max_length=250, unique=True),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='uniq_subcategory_slug_per_category'),
        ),
    ]
