# Generated by Django 6.1 on 2026-10-03 10:41

import products.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_slug_subcategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=products.fields.AutoSlugField(allow_unicode=True, blank=True, db_index=False, default='', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=products.fields.AutoSlugField(allow_unicode=True, blank=True, db_index=False, default='', max_length=150, unique_scope=('category',)),
        ),
    ]
